# Generated by Django 4.1 on 2022-08-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_board_description_alter_board_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='orderNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
